os:
- linux
language: python
python:
- '2.7'
- '3.5'
- '3.6'

# Travis python3.7 workaround
# See https://github.com/travis-ci/travis-ci/issues/9815
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

before_install:
- sudo apt-get update
- sudo apt-get install -y texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra latexmk texlive-luatex texlive-xetex

install:
- pip install tox-travis
- python setup.py install
script:
- tox

after_success:
- which python
- pip install sphinx-bazel
- cd docs
- make latexpdf

